// Builds a TEST-ONLY variant of the shipped .jsx.
//
// The problem: every gameplay handler (endMonth, handleInvest, handleFundraise, ...) is a closure
// inside the React component, so nothing at module scope can call them. The original Playwright
// harness solved this by driving the real UI in a browser. No browser is available here, and
// reimplementing the turn loop in the bot would violate the project's own standing lesson --
// a bot that approximates the engine tests the bot, not the engine.
//
// Instead: lift the handler block VERBATIM out of the component into a module-scope factory that
// supplies the only four things it closes over (setGame, language, t, knownCompanyNamesRef).
// The handler source text is never edited, so what the bot exercises is byte-identical to what
// ships. If the handler block moves, the anchors below fail loudly rather than silently
// extracting the wrong lines.
import fs from 'fs';

const SRC = process.argv[2] || 'founder-hospitality-prototype.jsx';
const OUT = process.argv[3] || 'harness-build.jsx';

const src = fs.readFileSync(SRC, 'utf8');
const lines = src.split('\n');

// Anchor on content, not line numbers, so a shifted file fails instead of mis-extracting.
const startIdx = lines.findIndex(l => l.includes('---- Business Model layer: commit and re-tool ----'));
const endAnchorIdx = lines.findIndex(l => l.includes('END HANDLER BLOCK'));

if (startIdx === -1) throw new Error('Could not find start anchor: function handleInvest(projectId) {');
if (endAnchorIdx === -1) throw new Error('Could not find end anchor: END HANDLER BLOCK sentinel');

// Walk back from the Render: Title comment to the last non-blank line (the closing brace of
// handleAttemptExit).
let endIdx = endAnchorIdx - 1;
while (endIdx > startIdx && (lines[endIdx].trim() === '' || lines[endIdx].trim().startsWith('//'))) endIdx--;
if (lines[endIdx].trim() !== '}') {
  throw new Error(`Expected handler block to end with '}', found: ${JSON.stringify(lines[endIdx])}`);
}

const handlerBlock = lines.slice(startIdx, endIdx + 1).join('\n');

// Sanity: the block must contain every handler the bots drive.
const REQUIRED = ['function handleInvest', 'function handleFundraise', 'function handleRecruit',
  'function handleLayoff', 'function handleRestCulture', 'function handleFundingInstrument',
  'function handlePivot', 'function handleExternalAction', 'function handleChoiceOption',
  'function endMonth', 'function handleAttemptExit', 'function handleOperate',
  'function handleCommitModel', 'function handleRetoolModel'];
const missing = REQUIRED.filter(r => !handlerBlock.includes(r));
if (missing.length) throw new Error('Handler block missing: ' + missing.join(', '));

const factory = `

// ==================== TEST HARNESS ONLY — not part of the shipped game ====================
// Generated by build_harness.mjs. The handler bodies below are lifted verbatim from the React
// component; do not edit them here. Edit the component and regenerate.
function __makeHandlers(language, knownNames) {
  let __state = null;
  const setGame = (u) => { __state = (typeof u === 'function') ? u(__state) : u; };
  const t = (text) => translate(text, language);
  const knownCompanyNamesRef = { current: knownNames || [] };

${handlerBlock}

  return {
    getState: () => __state,
    setState: (s) => { __state = s; },
    handleInvest, handleFundraise, handleRecruit, handleLayoff, handleRestCulture,
    handleFundingInstrument, handlePivot, handleExternalAction, handleChoiceOption,
    handleOperate, endMonth, handleAttemptExit, handleCommitModel, handleRetoolModel,
    handleSkunkworks,
    handleAdvanceProduct, handleLaunchProduct, handleIterateProduct, handleRetireProduct, handlePivotProduct,
    handleSetMaintenanceStance, handleReplaceEquipment,
    handleContractSupplier, handleCancelSupplierContract, handleSetInventoryStrategy, handleAcquireSupplier,
    handleHireManager, handleAssignManager, handleDismissManager,
    handleTakeDebt, handleFactorReceivables, handleTakeTradeCredit,
    handleBuildTier, handleAcquireRival, handleSellTier,
    handleEarlyAction,
    handleSetByproductPolicy,
    handleSetProductionStance, handleSetSalesStance,
    handleSpotBuy, handleSpotSell, handleToggleTierOpen,
    handleAcceptSalesContract, handleDeclineSalesContract, handleSolicitContract,
    handleScoutBuyers, handleAttendTradeShow, handleRequestIntroduction,
    handleSetMarketingPolicy, handleBrandCampaign,
  };
}

if (typeof window !== 'undefined') {
  window.__makeHandlers = __makeHandlers;
  window.__initialState = initialState;
  window.__getScenario = getScenario;
  window.__stageOf = stageOf;
  window.__computeMarketRank = computeMarketRank;
  window.__scaledProjectCost = scaledProjectCost;
  window.__instrumentsForStage2 = instrumentsForStage;
  window.__buildTeam = (typeof computeTeam === 'function') ? computeTeam : null;
  window.__getIndustry2 = getIndustry;
  window.__computeValuation = (typeof computeValuation === 'function') ? computeValuation : null;
}
`;

// Insert the factory immediately before the React component, matching the project's standing
// placement rule for the window.__ exposure block (after every top-level declaration).
const marker = 'export default function FounderHospitalityPrototype()';
const markerIdx = src.indexOf(marker);
if (markerIdx === -1) throw new Error('Could not find component export marker');

const out = src.slice(0, markerIdx) + factory + '\n' + src.slice(markerIdx);
fs.writeFileSync(OUT, out);
console.log(`Harness build written: ${OUT}`);
console.log(`  Lifted handler block: source lines ${startIdx + 1}-${endIdx + 1} (${endIdx - startIdx + 1} lines)`);
console.log(`  All ${REQUIRED.length} required handlers present.`);
